In [27]:
import pandas as pd

df = pd.read_csv('apt_price.csv',
                 encoding='UTF-8',
                 header=0)
df = df.drop(columns=['Unnamed: 0'])
display(df.head(10))

,NO,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),...,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형
0,1,경기도 수원시 영통구 매탄동,176,176,0,현대힐스테이트,75.8140,202312,31,"53,000",...,3,-,-,2006,권광로260번길 36,-,중개거래,경기 수원시영통구,24.02.28,아파트
1,2,경기도 의정부시 호원동,308-139,308,139,회룡역풍림아이원,84.9900,202312,31,"50,000",...,12,-,-,2007,외미로 64,-,중개거래,경기 의정부시,24.02.20,아파트
2,3,경기도 의정부시 호원동,308-139,308,139,회룡역풍림아이원,84.9900,202312,31,"50,000",...,12,-,-,2007,외미로 64,20240102,중개거래,경기 의정부시,-,아파트
3,4,경기도 성남시 중원구 금광동,3950,3950,0,삼익금광1차,44.0100,202312,31,"39,500",...,2,-,-,1991,자혜로16번길 9,-,중개거래,경기 성남시중원구,24.03.08,아파트
4,5,경기도 성남시 중원구 여수동,602,602,0,산들마을2단지,51.9300,202312,31,"60,000",...,1,-,-,2015,여수울로 51,-,중개거래,경기 성남시중원구,24.03.29,아파트
5,6,경기도 평택시 동삭동,852,852,0,평택센트럴자이3단지,84.2757,202312,31,"50,500",...,23,-,-,2019,상서재로 55,-,중개거래,경기 평택시,24.04.02,아파트
6,7,경기도 평택시 소사동,670,670,0,평택효성해링턴플레이스1단지,72.6500,202312,31,"35,500",...,8,-,-,2019,소사3로 53,-,중개거래,경기 평택시,24.02.23,아파트
7,8,경기도 평택시 고덕동,2489-1,2489,1,고덕국제신도시파라곤에듀포레,84.7996,202312,31,"59,000",...,7,-,-,2021,고덕국제8로 91,-,중개거래,경기 평택시,24.03.20,아파트
8,9,경기도 평택시 합정동,가-,0,0,평택뉴비전엘크루,84.9752,202312,31,"41,000",...,13,-,-,2021,소사7로 8,-,중개거래,경기 평택시,24.03.14,아파트
9,10,경기도 동두천시 생연동,473-9,473,9,화성아파트2차,59.6400,202312,31,"6,000",...,4,-,-,1990,평화로2452번길 15,-,중개거래,경기 동두천시,24.01.16,아파트

In [49]:
# 필터링할 지역 리스트 생성
target_areas = [
    '경기도 성남시 분당구 야탑동',
    '경기도 성남시 분당구 이매동',
    '경기도 성남시 분당구 서현동',
    '경기도 성남시 분당구 분당동',
    '경기도 성남시 분당구 수내동',
    '경기도 성남시 분당구 정자동',
    '경기도 성남시 분당구 금곡동',
    '경기도 성남시 분당구 구미동',
    '경기도 고양시 일산동구 식사동',
    '경기도 고양시 일산동구 중산동',
    '경기도 고양시 일산동구 정발산동',
    #'경기도 고양시 일산동구 풍산동',
    '경기도 고양시 일산동구 백석동',
    '경기도 고양시 일산동구 마두동',
    '경기도 고양시 일산동구 장항동',
    '경기도 고양시 일산서구 일산동',
    '경기도 고양시 일산서구 주엽동',
    '경기도 고양시 일산서구 대화동',
    '경기도 고양시 일산서구 탄현동'
]

# 시군구 컬럼이 target_areas에 포함된 데이터만 필터링
filtered_df = df[df['시군구'].isin(target_areas)]

# 거래금액 기준으로 정렬
# filtered_df = filtered_df.sort_values('거래금액(만원)', ascending=False)

# 결과 출력
display(filtered_df.head(10))
print(filtered_df.shape)

,NO,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),...,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형
138,139,경기도 성남시 분당구 정자동,180,180,0,미켈란쉐르빌,21.290,202312,30,"29,500",...,7,-,-,2003,정자일로 100,-,직거래,-,24.01.16,아파트
173,174,경기도 고양시 일산서구 주엽동,136,136,0,문촌마을13단지대우,74.460,202312,30,"39,300",...,8,-,-,1995,중앙로 1471,20240313,중개거래,경기 고양시일산동구,-,아파트
297,298,경기도 고양시 일산동구 중산동,1575-4,1575,4,중산마을11(현대),84.360,202312,29,"30,500",...,2,-,-,1995,탄중로 385,-,중개거래,경기 고양시일산동구,24.03.06,아파트
303,304,경기도 고양시 일산서구 탄현동,121,121,0,"큰마을대림,현대아파트",59.820,202312,29,"26,100",...,6,-,-,2001,일현로 140,20240113,중개거래,경기 고양일산서구,-,아파트
304,305,경기도 고양시 일산서구 주엽동,135,135,0,문촌마을15단지부영,40.270,202312,29,"28,800",...,5,-,-,1993,주엽로 123,-,중개거래,경기 고양시일산서구,24.02.26,아파트
305,306,경기도 고양시 일산서구 일산동,2125,2125,0,신원1,84.961,202312,29,"34,000",...,18,-,-,2002,일현로 8,-,직거래,-,24.02.14,아파트
401,402,경기도 성남시 분당구 수내동,36,36,0,양지마을(2단지)(청구),84.600,202312,29,"154,000",...,12,-,-,1992,내정로 185,-,중개거래,경기 성남시분당구,24.02.29,아파트
402,403,경기도 성남시 분당구 정자동,10-1,10,1,현대I-PARK2,162.010,202312,29,"203,000",...,18,-,-,2003,정자일로213번길 19,-,중개거래,"경기 성남시분당구, 서울 강동구",24.03.05,아파트
408,409,경기도 성남시 분당구 서현동,91,91,0,시범한양,28.710,202312,29,"55,000",...,8,-,-,1991,중앙공원로 17,-,중개거래,경기 성남시분당구,24.02.28,아파트
409,410,경기도 성남시 분당구 서현동,87,87,0,시범삼성,59.995,202312,29,"115,000",...,2,-,-,1991,중앙공원로 53,-,중개거래,경기 성남시분당구,24.04.30,아파트

(211356, 21)

In [47]:
# 데이터프레임의 컬럼 출력
print(df.columns)

Index(['NO', '시군구', '번지', '본번', '부번', '단지명', '전용면적(㎡)', '계약년월', '계약일',
       '거래금액(만원)', '동', '층', '매수자', '매도자', '건축년도', '도로명', '해제사유발생일', '거래유형',
       '중개사소재지', '등기일자', '주택유형'],
      dtype='object')

In [48]:
# 리스트로 여러 컬럼 지정
filtered_df = filtered_df.drop(['NO', '본번', '부번', '동', '층', '매수자', '매도자', '도로명', '해제사유발생일', '거래유형', '중개사소재지', '등기일자','주택유형'], axis=1, inplace=False)
display(filtered_df.head(15))

,시군구,번지,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),건축년도
138,경기도 성남시 분당구 정자동,180,미켈란쉐르빌,21.290,202312,30,"29,500",2003
173,경기도 고양시 일산서구 주엽동,136,문촌마을13단지대우,74.460,202312,30,"39,300",1995
297,경기도 고양시 일산동구 중산동,1575-4,중산마을11(현대),84.360,202312,29,"30,500",1995
303,경기도 고양시 일산서구 탄현동,121,"큰마을대림,현대아파트",59.820,202312,29,"26,100",2001
304,경기도 고양시 일산서구 주엽동,135,문촌마을15단지부영,40.270,202312,29,"28,800",1993
305,경기도 고양시 일산서구 일산동,2125,신원1,84.961,202312,29,"34,000",2002
401,경기도 성남시 분당구 수내동,36,양지마을(2단지)(청구),84.600,202312,29,"154,000",1992
402,경기도 성남시 분당구 정자동,10-1,현대I-PARK2,162.010,202312,29,"203,000",2003
408,경기도 성남시 분당구 서현동,91,시범한양,28.710,202312,29,"55,000",1991
409,경기도 성남시 분당구 서현동,87,시범삼성,59.995,202312,29,"115,000",1991
410,경기도 성남시 분당구 서현동,92,시범현대,59.550,202312,29,"95,500",1991
411,경기도 성남시 분당구 야탑동,211,매화마을(주공4),41.850,202312,29,"51,000",1993
412,경기도 성남시 분당구 야탑동,147,목련마을SK,59.930,202312,29,"53,000",1998
424,경기도 성남시 분당구 정자동,102,한솔마을(4단지)(주공),35.280,202312,29,"55,000",1994
586,경기도 고양시 일산서구 탄현동,121,"큰마을대림,현대아파트",59.820,202312,28,"24,000",2001